server:
  port: 1111


spring:
  application:
    name: forwardery
  datasource:
    url: jdbc:oracle:thin:@//192.168.102.35:1521/switchdb
    username: neousr
    password: Aa123456
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

corsConfig:
  allowedOrigin: http://localhost:${server.port}

jwt:
  secretKey: eyJhbGciOiJIUzI1NiJ9.eyJSb2xlIjoiQWRtaW4iLCJJc3N1ZXIiOiJJc3N1ZXIiLCJVc2VybmFtZSI6IkphdmFJblVzZSIsImV4cCI6MTcwMDYzODUzNywiaWF0IjoxNzAwNjM4NTM3fQ.cakxNusKVbUYfXIO_ldis-uQtQMxRO58Tktr31X6O_I
  expirationMinutes: 60

authentication:
  paths-to-bypass: /api-docs/**, /api-docs.yaml, /swagger-ui/**, /swagger-ui.html, /swagger-resources/**, /webjars/**, /favicon.ico, /management/**,/login/**

springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    disable-swagger-default-url: true
    persistAuthorization: true
    server-url: http://localhost:${server.port}
    doc-expansion: none
    tags-sorter: alpha
